---
version: 2.1

orbs:
  win: circleci/windows@5.0.0

executors:
  linux-x86_64:
    docker:
      - image: cimg/rust:1.82.0
  linux-aarch64:
    resource_class: arm.medium
    docker:
      - image: cimg/rust:1.82.0
  macos:
    macos:
      xcode: 16.1.0

jobs:
  test:
    executor: linux-x86_64
    steps:
      - checkout
      - run: cargo test --release
  build-linux-x86_64:
    executor: linux-x86_64
    steps:
      - checkout
      - run: cargo build --release
  build-linux-aarch64:
    executor: linux-aarch64
    steps:
      - checkout
      - run: cargo build --release
  build-macos:
    executor: macos
    steps:
      - checkout
      - run: curl -o rustup https://sh.rustup.rs
      - run: bash rustup -y
      - run: cargo build --release
  build-windows-x64:
    executor: win/server-2022
    steps:
      - checkout
      - run: curl -o rustup https://sh.rustup.rs
      - run: bash rustup -y
      - run: cargo build --release

workflows:
  test_and_build:
    jobs:
      - test
      - build-linux-x86_64:
          requires:
            - test
      - build-linux-aarch64:
          requires:
            - test
      - build-macos:
          requires:
            - test
      - build-windows-x64:
          requires:
            - test
