---
executors:
  linux_x86_64:
    docker:
      - image: cimg/rust:1.82.0
    resource_class: medium
  linux_arm64:
    docker:
      - image: cimg/rust:1.82.0
    resource_class: arm.medium
  macos:
    macos:
      xcode: 14.2.0
  windows:
    resource_class: windows.medium

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run: cargo test --release