---
version: 2.1
executors:
  linux-x86_64:
    docker:
      - image: cimg/rust
jobs:
  test:
    executor: linux-x86_64
    steps:
      - checkout
      - run: cargo test --release
workflows:
  test_and_build:
    jobs:
      - test
