on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - run: rustup update ${{ matrix.target }} && rustup default ${{ matrix.target }}
      - run: cargo build --verbose
      - run: cargo test --verbose
